project_id = "my-project-dev-469213"
credentails_file = "~/sa-key.json"
region       = "us-central1"
location     = "us-central1-a"
vpc_name     = "dev"
vpc_cidr     = "10.20.0.0/16"
cluster_name = "gke-autopilot-dev-cluster"
